AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon SQS message generator. Good for testing purposes.
Parameters:
  QueueNameParameter:
    Type: String
  NumberOfMessagesParameter:
    Type: Number
Resources:
  sqsmessagegenerator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        An Amazon SQS message generator.
      MemorySize: 128
      Timeout: 3
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource:
                - !Ref QueueNameParameter